name: Build Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  cancel:
    runs-on: ubuntu-latest
    name: Cancel previous jobs
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

  static_analysis:
    name: Lint, Unit Tests and Build
    needs:
      - cancel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Verify lint
        run: ./gradlew library:check
      - name: Execute coverage tests
        run: ./gradlew library:jacoco
      - name: Execute Assemble
        run: ./gradlew library:assemble