name: Build Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  static_analysis:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Verify lint
        run: ./gradlew library:check

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Execute coverage tests
        run: ./gradlew library:jacoco

  build_app:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Assemble
        run: ./gradlew library:assemble
